name: CompassCommand
version: 2.0.0
author: waterwood
description: A plugin enable that item binding command
main: waterfun.waterwood.compasscommand.CompassCommand

commands:
  compasscommand:
    aliases: ["cpc"]

permissions:
  compasscommand.*:
    description:  "ability to use all compasscommand commands"
    children:
      compasscommand.reload: true
  compasscommand.reload:
    default: op
    description: to reload the plugin
softdepend: [PlaceholderAPI]